local M = {}

function M.setup_hi()
  require "util".hi {
    { "TSComment", 						_G.colors.comments },
    { "TSAnnotation", 				_G.colors.blue },
    { "TSAttribute", 					_G.colors.cyan },
    { "TSConstructor", 				_G.colors.yellow },
    { "TSType", 							_G.colors.yellow },
    { "TSTypeBuiltin", 				_G.colors.yellow },
    { "TSConditional", 				_G.colors.purple },
    { "TSException", 					_G.colors.purple },
    { "TSInclude", 						_G.colors.purple },
    { "TSKeyword", 						_G.colors.purple },
    { "TSKeywordReturn", 			_G.colors.purple },
    { "TSKeywordFunction", 		_G.colors.purple },
    { "TSLabel", 							_G.colors.blue },
    { "TSNone", 							_G.colors.fg },
    { "TSNamespace", 					_G.colors.purple },
    { "TSRepeat", 						_G.colors.purple },
    { "TSConstant",					  _G.colors.orange },
    { "TSConstBuiltin", 			_G.colors.orange },
    { "TSFloat", 							_G.colors.orange },
    { "TSNumber", 						_G.colors.orange },
    { "TSBoolean", 						_G.colors.orange },
    { "TSCharacter", 					_G.colors.green },
    { "TSError", 							_G.colors.red },
    { "TSFunction", 					_G.colors.blue },
    { "TSFuncBuiltin", 				_G.colors.blue },
    { "TSMethod", 						_G.colors.blue },
    { "TSConstMacro", 				_G.colors.cyan },
    { "TSFuncMacro", 					_G.colors.blue },
    { "TSProperty", 					_G.colors.cyan },
    { "TSOperator", 					_G.colors.purple },
    { "TSField", 							_G.colors.blue },
    { "TSParameter", 					_G.colors.red },
    { "TSParameterReference", _G.colors.red },
    { "TSVariable", 					_G.colors.fg },
    { "TSVariableBuiltin", 		_G.colors.red },
    { "TSSymbol", 						_G.colors.cyan },
    { "TSText", 							_G.colors.fg },
    { "TSTextReference", 			_G.colors.red },
    { "TSPunctDelimiter", 		_G.colors.fg },
    { "TSTagDelimiter", 			_G.colors.comments },
    { "TSTagAttribute", 			_G.colors.orange },
    { "TSPunctBracket", 			_G.colors.fg },
    { "TSPunctSpecial", 			_G.colors.fg },
    { "TSString", 						_G.colors.green },
    { "TSStringRegex", 				_G.colors.orange },
    { "TSStringEscape", 			_G.colors.orange },
    { "TSTag", 								_G.colors.blue },
    { "TSEmphasis", 					nil, nil, "italic" },
    { "TSUnderline", 					nil, nil, "underline" },
    { "TSNote", 							_G.colors.yellow, nil, "bold" },
    { "TSWarning", 						_G.colors.orange, nil, "bold" },
    { "TSDanger", 						_G.colors.red, nil, "bold" },
    { "TSTitle", 							_G.colors.blue, nil, "bold" },
    { "TSLiteral", 						_G.colors.green },
    { "TSURI", 								_G.colors.blue, nil, "underline" },
    { "TSMath", 							_G.colors.fg },
    { "TSKeywordOperator", 		_G.colors.purple },
    { "TSStructure", 					_G.colors.fg },
    { "TSStrong", 						_G.colors.orange },
    { "TSQueryLinterError", 	_G.colors.orange },
    { "TSEnvironment", 				_G.colors.fg },
    { "TSEnvironmentName", 		_G.colors.fg },
  }
end

return M
