"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$directory$all"

[character]
success_symbol = "[»](bold green)"
error_symbol = "[](bold red)"

[cmd_duration]
min_time = 0
style = "white dimmed"
format = '[|](bright-black) [ $duration]($style) '

[directory]
truncate_to_repo = false

[git_branch]
style = "yellow"
symbol = "[ ](#f54c27)"
format = '[|](bright-black) [$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = '$all_status$ahead_behind '

conflicted = " [](bold red)"
ahead = " [](green)"
behind = " [](green)"
diverged = " [](yellow)"
untracked = " [](blue)"
stashed = " [](red dimmed)"
up_to_date = ""
modified = " [](yellow)"
staged = " [](green)"
renamed = " [](yellow)"
deleted = " [](red dimmed)"

[gcloud]
symbol = "[](cyan)"
format = '[|](bright-black) [$symbol](blue) [$project](cyan bold) [$account(@$domain )](blue dimmed)'

[terraform]
disabled = true

[nodejs]
symbol = " "
style = "yellow"
format = '[|](bright-black) [$symbol($version )]($style)'

[golang]
symbol = "[ﳑ](#79d4fd) "
style = "cyan dimmed"
format = '[|](bright-black) [$symbol($version )]($style)'

[rust]
style = "red"
format = '[|](bright-black) [$symbol($version )]($style)'

[buf]
style = "blue"
format = '[|](bright-black) [$symbol ($version )]($style)'

[package]
style = "208"
symbol = " "
format = '[|](bright-black) [$symbol($version) ]($style)'

[kubernetes]
disabled = false
style = "cyan"
format = '[|](bright-black) [$symbol$context ]($style)'