"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[»](bold green)"
error_symbol = "[×](bold red)"

[directory]
truncate_to_repo = false

[git_branch]
style = "bold green"
format = '[|](bright-black) [$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = '$all_status$ahead_behind '

conflicted = "[](bold red)"
ahead = "[﯁](green)"
behind = "[﮾](green)"
diverged = "[ﬕ](yellow)"
untracked = "[](yellow)"
stashed = "[](red dimmed)"
modified = "[](yellow dimmed)"
staged = "[](green)"
renamed = "[](yellow dimmed)"
deleted = "[](red dimmed)"

[gcloud]
symbol = "[](cyan)"
format = '[|](bright-black) [$symbol](blue) [$project](cyan bold) [$account(@$domain)](blue dimmed) '

[terraform]
disabled = true

[nodejs]
symbol = " "
style = "yellow"
format = "[|](bright-black) [$symbol($version)]($style) "

[golang]
symbol = "ﳑ "
style = "cyan"
format = '[|](bright-black) [$symbol($version)]($style) '